spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/aifa
    username: postgres
    password: Jtatum230100
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    com.aifa: DEBUG
    org.springframework.security: INFO
